version: '3.8'
services:
  db:
    image: postgres:14.15-alpine3.20
    restart: always
    environment:
      POSTGRES_USER: myuser       # Имя пользователя для БД
      POSTGRES_PASSWORD: root   # Пароль для пользователя
      POSTGRES_DB: restdb           # Имя создаваемой базы данных
    ports:
      - "5432:5432"              # Проброс порта: внешний:внутренний
