version: '3.8'
services:
  db:
    image: postgres:14.15-alpine3.20
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: root
      POSTGRES_DB: restdb
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: